-- PostgreSQL schema for the application. SQLite's local/source schema is schema.sqlite.sql.

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  google_sub    TEXT UNIQUE,
  avatar_url    TEXT,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_product_id     TEXT UNIQUE,
  name                  TEXT NOT NULL,
  description           TEXT,
  price                 DOUBLE PRECISION NOT NULL CHECK (price >= 0),
  image_url             TEXT,
  category              TEXT,
  stock                 INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  subcategory           TEXT,
  brand                 TEXT,
  variant_specification TEXT,
  mrp_inr               DOUBLE PRECISION,
  discount_percent      DOUBLE PRECISION,
  quality               TEXT,
  rating_stars          DOUBLE PRECISION,
  review_count          INTEGER,
  manufacturing_date    TEXT,
  expiry_date           TEXT,
  voltage               TEXT,
  power_rating          TEXT,
  age_range             TEXT,
  warranty              TEXT,
  seller                TEXT,
  country_of_origin     TEXT,
  return_period_days    INTEGER,
  product_status        TEXT,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity   INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS orders (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  total_amount DOUBLE PRECISION NOT NULL CHECK (total_amount >= 0),
  status       TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','confirmed','shipped','delivered','cancelled')),
  shipping_name TEXT,
  shipping_address TEXT,
  shipping_phone TEXT,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  quantity   INTEGER NOT NULL CHECK (quantity > 0),
  price      DOUBLE PRECISION NOT NULL CHECK (price >= 0),
  UNIQUE (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS product_reviews (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating     INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (product_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_product_reviews_product_created
  ON product_reviews(product_id, created_at DESC);

CREATE TABLE IF NOT EXISTS wishlist_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS compare_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, product_id)
);
